### ISSUE TITLE
Monitoring: WhatsApp notification channel

### ISSUE THREAD

**Issue by joschi99** [joschi99/Osiris#41]
Create the possibility to use WhatsApp as a alternative notification channel for monitoring notifications using yowsup (https://github.com/tgalal/yowsup)

**Comment by joschi99** [comment]
Install yowsup2
`pip install yowsup2`

Upgrade yowsup2
`pip install --upgrade yowsup2`

**Comment by joschi99** [comment]
With version 2.4.102 it is not possible to register to WhatsApp:

- status: fail 
- reason: old_version

for more details see https://github.com/tgalal/yowsup/issues/1537

**Comment by jonatascalebe** [comment]
I use the soluction on https://github.com/tgalal/yowsup/issues/1537 #1537 from @rafaelsilverioit and work fine.

**Comment by joschi99** [comment]
After succesfull registration sending a messsage produce the following error:
`yowsup-cli demos -s 39335xxxxxxx "Hallo Welt" -c /etc/yowsup2/yowsup2.cfg`

```
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/bin/yowsup-cli", line 323, in startSendClient
    not self.args["unmoxie"])
  File "/usr/lib/python2.6/site-packages/yowsup/demos/sendclient/stack.py", line 21, in __init__
    .push(SendLayer)\
  File "/usr/lib/python2.6/site-packages/yowsup/stacks/yowstack.py", line 64, in build
    return YowStack(self.layers, reversed = False, props = self._props)
  File "/usr/lib/python2.6/site-packages/yowsup/stacks/yowstack.py", line 135, in __init__
    self._construct()
  File "/usr/lib/python2.6/site-packages/yowsup/stacks/yowstack.py", line 206, in _construct
    inst = s()
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/layer.py", line 43, in __init__
    super(YowAxolotlLayer, self).__init__()
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init__.py", line 115, in __init__
    super(YowProtocolLayer, self).__init__()
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init__.py", line 47, in __init__
    members = inspect.getmembers(self, predicate=inspect.ismethod)
  File "/usr/lib64/python2.6/inspect.py", line 252, in getmembers
    value = getattr(object, key)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/layer.py", line 55, in store
    if self._store is None:
AttributeError: 'YowAxolotlLayer' object has no attribute '_store'
```
see https://github.com/tgalal/yowsup/issues/1460 for more infos

**Comment by joschi99** [comment]
upgrade to yowsup 2.5.0:
```
pip install --upgrade pip
pip install --upgrade setuptools
pip install --upgrade yowsup2
```
